In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./dataset/산불발생일자19841201-20140619.csv')
df.head()

,Unnamed: 0,발생일시,발생일시(요일),진화일시(년월일시분),진화소요시간(분),발생장소(관서),발생장소(시도),발생장소(시군구),발생장소(읍면동),발생장소(리),...,평균기온,실효습도,상대습도,최소습도,최대풍속,평균풍속,최대풍향,평균풍향,강우결과일수,최종강우량
0,0,201406191500,목,201406191800,300,북부,강원,인제,남,남전,...,23.6,0.0,57.0,0.0,5.6,1.9,S,SE,6,0.5
1,1,201406181805,수,201406182015,210,경남,경남,밀양,삼랑진,미전,...,29.6,0.0,46.0,0.0,4.0,2.4,SE,NNE,6,1.5
2,2,201406151410,일,201406151720,310,강원,강원,인제,인제,가아,...,29.3,0.0,57.0,0.0,6.7,1.3,SSW,NW,2,0.5
3,3,201406141720,토,201406141900,140,전북,전북,부안,보안,신복,...,25.3,0.0,46.0,0.0,7.8,3.3,W,WNW,3,1.5
4,4,201406101718,화,201406102000,242,북부,강원,원주,흥업,매지,...,22.3,0.0,40.0,0.0,9.9,2.0,SSE,NNE,1,0.5

In [3]:
df.tail()

,Unnamed: 0,발생일시,발생일시(요일),진화일시(년월일시분),진화소요시간(분),발생장소(관서),발생장소(시도),발생장소(시군구),발생장소(읍면동),발생장소(리),...,평균기온,실효습도,상대습도,최소습도,최대풍속,평균풍속,최대풍향,평균풍향,강우결과일수,최종강우량
10195,10195,198412271900,목,198412272130,230,경북,경북,영천,임고,수성,...,-3.5,0.0,47.0,0.0,0.0,3.5,,NW,18,1.0
10196,10196,198412091300,일,198412091320,20,서울,서울,은평,불광,,...,13.3,0.0,34.0,0.0,0.0,3.0,,E,4,0.6
10197,10197,198412031150,월,198412031215,25,부산,부산,동래,명륜,,...,13.4,0.0,43.0,0.0,0.0,3.3,,W,10,2.7
10198,10198,198412021445,일,198412022145,700,경북,경북,청도,각남,옥산,...,10.6,0.0,19.0,0.0,0.0,4.0,,NNW,13,0.7
10199,10199,198412011505,토,198412011640,135,전남,전남,여수,상암,,...,11.8,0.0,35.0,0.0,0.0,9.2,,NW,17,9.3

In [4]:
df.columns

Index(['Unnamed: 0', '발생일시', '발생일시(요일)', '진화일시(년월일시분)', '진화소요시간(분)',
       '발생장소(관서)', '발생장소(시도)', '발생장소(시군구)', '발생장소(읍면동)', '발생장소(리)', '발생장소(지번)',
       '소유구분', '발생세부원인', '피해면적', '피해액', '산불위험지수(평균)', '산불위험지수(최대)', '평균기온',
       '실효습도', '상대습도', '최소습도', '최대풍속', '평균풍속', '최대풍향', '평균풍향', '강우결과일수',
       '최종강우량'],
      dtype='object')

In [5]:
df['발생세부원인'].value_counts()

입산자실화추정       2400
입산자실화         1624
쓰레기소각          639
논밭두렁소각         538
성묘객실화          491
              ...
움막화재확산           1
등산객담뱃불실화추정       1
수산폐기물소각추정        1
연탄재투기에의한실화       1
군부대사격            1
Name: 발생세부원인, Length: 590, dtype: int64

In [6]:
df['발생세부원인'].values

array(['쓰레기소각', '담뱃불실화 추정', '도로공사(용접불티)비화', ..., '입산자실화', '입산자실화',
       '입산자실화'], dtype=object)

In [7]:
df['최대풍향'].value_counts()

       8878
WNW     135
WSW     133
W       120
SW      113
NW      106
SSW      93
NNW      88
N        82
S        77
E        58
ENE      57
SSE      56
ESE      53
NNE      50
SE       48
NE       42
정온        8
7         1
NS        1
NN        1
Name: 최대풍향, dtype: int64

In [8]:
df['실효습도'].describe()

count    10200.000000
mean         3.797980
std         12.695908
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         97.000000
Name: 실효습도, dtype: float64

In [9]:
df['발생장소(시도)'].values

array(['강원', '경남', '강원', ..., '부산', '경북', '전남'], dtype=object)

In [10]:
location = pd.DataFrame(df.groupby('발생장소(시도)'))[0].values.tolist()

In [11]:
location

['강원',
 '경기',
 '경남',
 '경북',
 '광주',
 '대구',
 '대전',
 '부산',
 '서부',
 '서울',
 '세종',
 '울산',
 '인천',
 '전남',
 '전북',
 '전주',
 '제주',
 '출북',
 '충남',
 '충북']

In [12]:
강원 = df[df['발생장소(시도)'] ==  '강원']
경기 = df[df['발생장소(시도)'] ==  '경기']
경남 = df[df['발생장소(시도)'] ==  '경남']
경북 = df[df['발생장소(시도)'] ==  '경북']
광주 = df[df['발생장소(시도)'] ==  '광주']
대구 = df[df['발생장소(시도)'] ==  '대구']
대전 = df[df['발생장소(시도)'] ==  '대전']
부산 = df[df['발생장소(시도)'] ==  '부산']
서부 = df[df['발생장소(시도)'] ==  '서부']
서울 = df[df['발생장소(시도)'] ==  '서울']
세종 = df[df['발생장소(시도)'] ==  '세종']
울산 = df[df['발생장소(시도)'] ==  '울산']
인천 = df[df['발생장소(시도)'] ==  '인천']
전남 = df[df['발생장소(시도)'] ==  '전남']
전북 = df[df['발생장소(시도)'] ==  '전북']
전주 = df[df['발생장소(시도)'] ==  '전주']
제주 = df[df['발생장소(시도)'] ==  '제주']
출북 = df[df['발생장소(시도)'] ==  '출북']
충남 = df[df['발생장소(시도)'] ==  '충남']
충북 = df[df['발생장소(시도)'] ==  '충북']

In [13]:
강원['발생장소(시군구)'].value_counts()

춘천    196
강릉    154
홍천    152
원주    111
인제     95
삼척     88
영월     87
횡성     85
평창     66
고성     65
정선     61
양양     58
화천     47
양구     45
태백     40
동해     36
철원     32
속초     16
Name: 발생장소(시군구), dtype: int64

In [14]:
강원['최대풍향'].value_counts()

       1229
WSW      25
SW       24
SSW      20
NW       15
W        14
N        14
WNW      14
S        13
ESE      10
NE        9
SSE       9
ENE       9
E         8
NNW       8
SE        7
NNE       4
NS        1
정온        1
Name: 최대풍향, dtype: int64

In [15]:
강원['발생일시']=강원['발생일시'].astype(str)

C:\Users\wease\AppData\Local\Temp\ipykernel_9360\2019339622.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  강원['발생일시']=강원['발생일시'].astype(str)

In [16]:
강원['발생일시'] = pd.to_datetime(강원['발생일시'])

C:\Users\wease\AppData\Local\Temp\ipykernel_9360\3096232626.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  강원['발생일시'] = pd.to_datetime(강원['발생일시'])

In [17]:
강원

,Unnamed: 0,발생일시,발생일시(요일),진화일시(년월일시분),진화소요시간(분),발생장소(관서),발생장소(시도),발생장소(시군구),발생장소(읍면동),발생장소(리),...,평균기온,실효습도,상대습도,최소습도,최대풍속,평균풍속,최대풍향,평균풍향,강우결과일수,최종강우량
0,0,2014-06-19 15:00:00,목,201406191800,300,북부,강원,인제,남,남전,...,23.6,0.0,57.0,0.0,5.6,1.9,S,SE,6,0.5
2,2,2014-06-15 14:10:00,일,201406151720,310,강원,강원,인제,인제,가아,...,29.3,0.0,57.0,0.0,6.7,1.3,SSW,NW,2,0.5
4,4,2014-06-10 17:18:00,화,201406102000,242,북부,강원,원주,흥업,매지,...,22.3,0.0,40.0,0.0,9.9,2.0,SSE,NNE,1,0.5
8,8,2014-06-01 21:45:00,일,201406020150,405,강원,강원,횡성,갑천,상대,...,25.4,0.0,51.0,0.0,1.9,1.1,N,SSW,6,5.0
11,11,2014-05-31 17:02:00,토,201405311904,202,동부,강원,평창,미탄,평안,...,32.4,0.0,25.0,0.0,5.6,7.9,WSW,NNE,5,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10189,1985-03-02 17:20:00,토,198503021730,10,강원,강원,춘천,삼천,,...,7.5,0.0,62.0,0.0,0.0,0.0,,정온,10,3.1
10190,10190,1985-03-02 17:10:00,토,198503021712,2,강원,강원,춘천,서,안보,...,7.5,0.0,62.0,0.0,0.0,0.0,,정온,10,3.1
10191,10191,1985-02-25 15:50:00,월,198502251600,10,강원,강원,춘천,옥천,,...,1.5,0.0,35.0,0.0,0.0,1.0,,E,5,3.1
10192,10192,1985-02-25 14:10:00,월,198502251430,20,강원,강원,춘천,남산,서천,...,2.2,0.0,37.0,0.0,0.0,0.2,,정온,5,3.1
10193,10193,1985-02-23 22:30:00,토,198502232300,30,강원,강원,동해,삼화,,...,-6.1,0.0,34.0,0.0,0.0,3.3,,W,4,3.4

In [18]:
강원['Month'] = 강원['발생일시'].dt.month
강원['Month'].value_counts()

C:\Users\wease\AppData\Local\Temp\ipykernel_9360\53200874.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  강원['Month'] = 강원['발생일시'].dt.month

4     570
3     243
5     159
2     133
11     76
12     74
1      66
10     54
6      53
8       4
9       1
7       1
Name: Month, dtype: int64

In [19]:
spring = 강원[(강원['Month'] == 3)| (강원['Month'] == 4) |(강원['Month'] == 5)]

In [20]:
spring

,Unnamed: 0,발생일시,발생일시(요일),진화일시(년월일시분),진화소요시간(분),발생장소(관서),발생장소(시도),발생장소(시군구),발생장소(읍면동),발생장소(리),...,실효습도,상대습도,최소습도,최대풍속,평균풍속,최대풍향,평균풍향,강우결과일수,최종강우량,Month
11,11,2014-05-31 17:02:00,토,201405311904,202,동부,강원,평창,미탄,평안,...,0.0,25.0,0.0,5.6,7.9,WSW,NNE,5,6.5,5
16,16,2014-05-30 10:00:00,금,201405301400,400,동부,강원,삼척,도계,점,...,0.0,24.0,0.0,5.3,3.5,NW,NNW,2,5.0,5
20,20,2014-05-28 15:40:00,수,201405281905,325,북부,강원,양구,남,명곶,...,0.0,86.0,0.0,5.5,1.4,SSW,SSE,2,2.0,5
24,24,2014-05-26 12:10:00,월,201405261410,200,강원,강원,삼척,근덕,교곡,...,0.0,76.0,0.0,11.8,4.7,WNW,W,1,1.0,5
41,41,2014-05-14 18:24:00,수,201405141940,116,동부,강원,정선,임계,가목,...,0.0,23.0,0.0,7.0,1.2,SSE,WSW,2,16.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10184,10184,1985-03-22 14:12:00,금,198503221500,48,강원,강원,원주,지정,안창,...,0.0,30.0,0.0,0.0,1.0,,NE,14,16.6,3
10185,10185,1985-03-22 14:00:00,금,198503221430,30,강원,강원,춘천,퇴계,,...,0.0,33.0,0.0,0.0,1.3,,SW,14,9.7,3
10187,10187,1985-03-20 13:30:00,수,198503201340,10,강원,강원,강릉,구정,제비,...,0.0,45.0,0.0,0.0,2.3,,ENE,6,1.7,3
10189,10189,1985-03-02 17:20:00,토,198503021730,10,강원,강원,춘천,삼천,,...,0.0,62.0,0.0,0.0,0.0,,정온,10,3.1,3
10190,10190,1985-03-02 17:10:00,토,198503021712,2,강원,강원,춘천,서,안보,...,0.0,62.0,0.0,0.0,0.0,,정온,10,3.1,3

In [21]:
강원['발생일시(요일)'].value_counts()

일    263
월    210
수    207
금    200
목    198
화    185
토    171
Name: 발생일시(요일), dtype: int64

In [22]:
강원['hour'] = 강원['발생일시'].dt.hour

C:\Users\wease\AppData\Local\Temp\ipykernel_9360\1755350622.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  강원['hour'] = 강원['발생일시'].dt.hour

In [23]:
강원['hour'].value_counts()

14    240
13    221
15    180
12    167
16    127
11    126
17     71
10     60
19     38
18     32
21     20
9      17
20     17
3      16
4      15
2      14
23     12
22     12
8      11
5      11
1       8
7       7
6       6
0       6
Name: hour, dtype: int64