In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('test_sample.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 39 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  24 non-null     int64
 1   tm          24 non-null     object
 2   rnum        24 non-null     int64
 3   stnId       24 non-null     int64
 4   stnNm       24 non-null     object
 5   ta          24 non-null     float64
 6   taQcflg     0 non-null      float64
 7   rn          0 non-null      float64
 8   rnQcflg     0 non-null      float64
 9   ws          24 non-null     float64
 10  wsQcflg     0 non-null      float64
 11  wd          24 non-null     int64
 12  wdQcflg     0 non-null      float64
 13  hm          24 non-null     int64
 14  hmQcflg     0 non-null      float64
 15  pv          24 non-null     float64
 16  td          24 non-null     float64
 17  pa          24 non-null     float64
 18  paQcflg     0 non-null      float64
 19  ps          24 non-null     float64
 20  psQcflg     0 non-null      float64
 21  ss          15 non-null     float64
 22  ssQcflg     9 non-null      float64
 23  icsr        15 non-null     float64
 24  dsnw        0 non-null      float64
 25  hr3Fhsc     0 non-null      float64
 26  dc10Tca     24 non-null     int64
 27  dc10LmcsCa  24 non-null     int64
 28  clfmAbbrCd  5 non-null      object
 29  lcsCh       6 non-null      float64
 30  vs          24 non-null     int64
 31  gndSttCd    0 non-null      float64
 32  dmstMtphNo  7 non-null      float64
 33  ts          24 non-null     float64
 34  tsQcflg     0 non-null      float64
 35  m005Te      0 non-null      float64
 36  m01Te       0 non-null      float64
 37  m02Te       0 non-null      float64
 38  m03Te       0 non-null      float64
dtypes: float64(28), int64(8), object(3)
memory usage: 7.4+ KB

In [4]:
df_small = df[['tm','stnNm','ta','rn','ws','wd','hm']]
df_small.columns = ['일시','지점명','기온','강수량','풍속','풍향','습도']
df_small

                  일시 지점명    기온  강수량   풍속   풍향  습도
0   2020-04-24 00:00  안동   5.0  NaN  1.9  290  40
1   2020-04-24 01:00  안동   4.9  NaN  0.6  250  45
2   2020-04-24 02:00  안동   4.1  NaN  0.8  290  50
3   2020-04-24 03:00  안동   4.3  NaN  0.7  320  51
4   2020-04-24 04:00  안동   3.7  NaN  1.1  290  55
5   2020-04-24 05:00  안동   3.2  NaN  2.3  290  60
6   2020-04-24 06:00  안동   3.0  NaN  1.4  320  63
7   2020-04-24 07:00  안동   3.7  NaN  1.0  320  62
8   2020-04-24 08:00  안동   6.3  NaN  1.6  250  56
9   2020-04-24 09:00  안동   8.6  NaN  2.3  270  53
10  2020-04-24 10:00  안동  10.6  NaN  3.2  270  42
11  2020-04-24 11:00  안동  12.7  NaN  4.9  290  31
12  2020-04-24 12:00  안동  14.1  NaN  5.9  270  25
13  2020-04-24 13:00  안동  14.5  NaN  6.5  270  22
14  2020-04-24 14:00  안동  15.7  NaN  5.9  270  22
15  2020-04-24 15:00  안동  16.0  NaN  6.7  270  20
16  2020-04-24 16:00  안동  16.4  NaN  6.5  290  18
17  2020-04-24 17:00  안동  15.7  NaN  6.8  270  19
18  2020-04-24 18:00  안동  14.6  NaN  6.0  270  21
19  2020-04-24 19:00  안동  13.3  NaN  5.2  270  24
20  2020-04-24 20:00  안동  12.5  NaN  5.0  290  25
21  2020-04-24 21:00  안동  11.5  NaN  1.7  250  29
22  2020-04-24 22:00  안동  10.6  NaN  1.8  270  30
23  2020-04-24 23:00  안동   9.3  NaN  0.6  270  34

In [5]:
df_small['실효습도'] = [42.31, 44.85, 47.10, 47.91, 49.25, 51.81, 54.07, 52.63, 48.01, 42.23, 34.74, 29.13, 26.01, 24.06, 22.96, 21.91, 21.06, 22.06, 24.99, 27.75, 29.63, 31.81, 31.35, 33.70]
df_small

C:\Users\yujeyeong\AppData\Local\Temp\ipykernel_27772\1169476006.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_small['실효습도'] = [42.31, 44.85, 47.10, 47.91, 49.25, 51.81, 54.07, 52.63, 48.01, 42.23, 34.74, 29.13, 26.01, 24.06, 22.96, 21.91, 21.06, 22.06, 24.99, 27.75, 29.63, 31.81, 31.35, 33.70]

                  일시 지점명    기온  강수량   풍속   풍향  습도   실효습도
0   2020-04-24 00:00  안동   5.0  NaN  1.9  290  40  42.31
1   2020-04-24 01:00  안동   4.9  NaN  0.6  250  45  44.85
2   2020-04-24 02:00  안동   4.1  NaN  0.8  290  50  47.10
3   2020-04-24 03:00  안동   4.3  NaN  0.7  320  51  47.91
4   2020-04-24 04:00  안동   3.7  NaN  1.1  290  55  49.25
5   2020-04-24 05:00  안동   3.2  NaN  2.3  290  60  51.81
6   2020-04-24 06:00  안동   3.0  NaN  1.4  320  63  54.07
7   2020-04-24 07:00  안동   3.7  NaN  1.0  320  62  52.63
8   2020-04-24 08:00  안동   6.3  NaN  1.6  250  56  48.01
9   2020-04-24 09:00  안동   8.6  NaN  2.3  270  53  42.23
10  2020-04-24 10:00  안동  10.6  NaN  3.2  270  42  34.74
11  2020-04-24 11:00  안동  12.7  NaN  4.9  290  31  29.13
12  2020-04-24 12:00  안동  14.1  NaN  5.9  270  25  26.01
13  2020-04-24 13:00  안동  14.5  NaN  6.5  270  22  24.06
14  2020-04-24 14:00  안동  15.7  NaN  5.9  270  22  22.96
15  2020-04-24 15:00  안동  16.0  NaN  6.7  270  20  21.91
16  2020-04-24 16:00  안동  16.4  NaN  6.5  290  18  21.06
17  2020-04-24 17:00  안동  15.7  NaN  6.8  270  19  22.06
18  2020-04-24 18:00  안동  14.6  NaN  6.0  270  21  24.99
19  2020-04-24 19:00  안동  13.3  NaN  5.2  270  24  27.75
20  2020-04-24 20:00  안동  12.5  NaN  5.0  290  25  29.63
21  2020-04-24 21:00  안동  11.5  NaN  1.7  250  29  31.81
22  2020-04-24 22:00  안동  10.6  NaN  1.8  270  30  31.35
23  2020-04-24 23:00  안동   9.3  NaN  0.6  270  34  33.70

In [ ]:
df.small.to_csv('test_sample_2020.csv')